pipeline:
  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
      - DEPLOY_ENV=dev
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      environment: secrets
      event: deployment

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t cop-test-reports:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
    - source: QUAY_PASSWORD
      target: DOCKER_PASSWORD
    - source: QUAY_USERNAME
      target: DOCKER_USERNAME
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/cop-test-reports
    tags: ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: DEV_COP_TEST_REPORTS_NAME
        target: NAME
      - source: DEV_KUBE_NAMESPACE_PRIVATE_COP
        target: KUBE_NAMESPACE
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: DEV_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_COP_TEST_REPORTS_KEYCLOAK_SECRET
        target: KEYCLOAK_SECRET
      - source: DEV_COP_TEST_REPORTS_KEYCLOAK_CLIENT_ID
        target: KEYCLOAK_CLIENT_ID
      - source: DEV_COP_TEST_REPORTS_KEYCLOAK_SESSION_NAME
        target: KEYCLOAK_SESSION_NAME
      - source: DEV_WHITELIST
        target: WHITELIST
      - source: DEV_COP_TEST_REPORTS_PORT
        target: PORT
      - source: TESTS_S3_ACCESS_KEY
        target: S3_ACCESS_KEY_ID
      - source: S3_BUCKET_NAME
        target: DEV_S3_BUCKET
      - source: TESTS_S3_SECRET_KEY
        target: S3_SECRET_ACCESS_KEY
      - source: DEV_COP_TEST_REPORTS_TEST_REPORT_PREFIX
        target: S3_TEST_REPORT_PREFIX
    commands:
      - export IMAGE_TAG=${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/secret.yml
      - kd --insecure-skip-tls-verify -f kube/network-policy.yml
      - kd --insecure-skip-tls-verify -f kube/service.yml
      - kd --insecure-skip-tls-verify -f kube/deployment.yml --timeout=5m
      - kd --insecure-skip-tls-verify -f kube/ingress.yml
    when:
      branch: master
      event: push

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
