---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .NAME }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: "{{ .NAME }}"
        service: "{{ .NAME }}"
    spec:
      containers:  
        - name: "{{ .NAME }}"
          image: quay.io/ukhomeofficedigital/{{ .NAME }}:{{ .IMAGE_TAG }}
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "{{ .PORT }}"
          - name: S3_TEST_REPORT_PREFIX
            value: "{{ .S3_TEST_REPORT_PREFIX }}"
          - name: KEYCLOAK_CLIENT_ID
            value: "{{ .KEYCLOAK_CLIENT_ID }}"
          - name: KEYCLOAK_URL
            value: "{{ .KEYCLOAK_URL }}"
          - name: KEYCLOAK_REALM
            value: "{{ .KEYCLOAK_REALM }}"
          - name: KEYCLOAK_SESSION_NAME
            value: "{{ .KEYCLOAK_SESSION_NAME }}"

          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: "{{ .NAME }}"
                key: aws_access_key
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: "{{ .NAME }}"
                key: aws_secret_access_key
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: "{{ .NAME }}"
                key: aws_s3_bucket
          - name: KEYCLOAK_SECRET
            valueFrom:
              secretKeyRef:
                name: "{{ .NAME }}"
                key: keycloak_secret
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512M"  
              cpu: "500m"
            limits:
              memory: "1024M"
              cpu: "1"
          securityContext:
            runAsUser: 1000  
