---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .NAME }}"
type: Opaque
data:
  aws_access_key: "{{ .S3_ACCESS_KEY_ID | b64enc }}"
  aws_secret_access_key: "{{ .S3_SECRET_ACCESS_KEY | b64enc }}"
  aws_s3_bucket: "{{ .S3_BUCKET | b64enc }}"
  keycloak_secret: "{{ .KEYCLOAK_SECRET | b64enc }}"

