---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .NAME }}"
  labels:
    app: "{{ .NAME }}"
spec:
  ports:
  - name: https
    port: 3000
    targetPort: 3000
  selector:
    name: "{{ .NAME }}"
  type: ClusterIP
